spring.application.name=wallet
spring.jpa.hibernate.ddl-auto=update
# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=user
spring.datasource.password=password

# AWS LocalStack
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test


# Nomes configurados no script
events.sns.topic-arn=wallet-events-topic
events.sqs.queue-url=wallet-events-queue
